[package]
name = "dodo"
version = "0.1.0"
edition = "2021"
authors = ["0x6c6d"]
description = "CLI tool for analyzing solidity smart contract binaries"

[dependencies]
hex = "0.4.3"
clap = { version = "4.5.4", features = ["derive"] }
